#=======================================
# LOGGING
#=======================================
quarkus.log.level=INFO
quarkus.log.category."org.jboss.sbomer".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss,SSS} %-5p traceId=%X{traceId} parentId=%X{parentId} spanId=%X{spanId} [%c{3.}] (%t) %s%e mdc:[%X]%n

#=======================================
# OBSERVABILITY
#=======================================
quarkus.otel.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.traces.sampler=always_on
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true

#=======================================
# APPLICATION
#=======================================

# The base URL for the OWASP Dependency Track instance
dtrack-api/mp-rest/url=${DTRACK_API_URL}
# The API key generated in the D-Track UI (needs PORTFOLIO_MANAGEMENT permission)
dtrack.api.key=${DTRACK_API_KEY}

manifest.storage.internal.url=${MANIFEST_STORAGE_INTERNAL_URL}

#=======================================
# KAFKA - GLOBAL PRODUCER CONFIG
#=======================================
# These settings apply to ALL outgoing Kafka channels
kafka.apicurio.registry.auto-register=true
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}
kafka.apicurio.registry.url=${SCHEMA_REGISTRY_URL}

#=======================================
# KAFKA - CHANNEL DEFINITIONS
#=======================================

# OUTGOING

# --- 'sbomer-errors' channel ---
mp.messaging.outgoing.sbomer-errors.topic=sbomer.errors
mp.messaging.outgoing.sbomer-errors.connector=smallrye-kafka
mp.messaging.outgoing.sbomer-errors.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.sbomer-errors.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.outgoing.sbomer-errors.apicurio.registry.auto-register=true

# --- 'publish-finished' channel ---
mp.messaging.outgoing.publish-finished.topic=publish.finished
mp.messaging.outgoing.publish-finished.connector=smallrye-kafka
mp.messaging.outgoing.publish-finished.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.publish-finished.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.outgoing.publish-finished.apicurio.registry.auto-register=true

# INCOMING

# --- 'requests-finished' channel ---
mp.messaging.incoming.requests-finished.topic=requests.finished
mp.messaging.incoming.requests-finished.connector=smallrye-kafka
mp.messaging.incoming.requests-finished.value.deserializer=io.apicurio.registry.serde.avro.AvroKafkaDeserializer
mp.messaging.incoming.requests-finished.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.incoming.requests-finished.apicurio.registry.auto-register=true
mp.messaging.incoming.requests-finished.apicurio.registry.use-specific-avro-reader=true